name: C/C++ CI

on:
  push:
    branches: [ master, conan ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: conan package
      run: pip3 install conan && pip3 show -f conan && $HOME/.local/bin/conan create . oracle2025/cmake_simple_lib
