name: C/C++ CI

on:
  push:
    branches: [ master, conan ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: conan package
      run: pip install conan && pip show -f conan && echo $PATH && conan create . oracle2025/cmake_simple_lib
    - name: conan deploy
      env:
         BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: conan remote add cmake_simple_lib https://api.bintray.com/conan/oracle2025/cmake_simple_lib && conan user -p "$BINTRAY_API_KEY" -r cmake_simple_lib oracle2025 && conan upload -c -r cmake_simple_lib cmake_simple_lib/0.1
